language: python
python:
  - "3.4"
  - "3.5"
install:
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=model,encdec,handlers setup.py test
after_success:
  - coveralls
