language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=model,encdec,client setup.py test
after_success:
  - coveralls
